IJZPO/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('record.urls')),
    url(r'', include('allauth.urls'))

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

record/urls.py
from django.conf.urls import url
from .import views
from django_filters.views import FilterView
from .filters import applicationsfilter


app_name = 'records'

urlpatterns = [
    url(r'^$', views.indexview.as_view(), name='index'),
    url(r'^applications$', views.applicationsview.as_view(), name='applications'),
    url(r'^map$', views.mapsview.as_view(), name='maps'),
    url(r'^new$', views.CreateApplication.as_view(), name='createapplication'),
    url(r'^update/(?P<pk>[0-9]+)$', views.applicationupdate.as_view(), name='updateapplication'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.applicationdelete.as_view(), name='deleteapplication'),
    url(r'^search/$', views.search, name='search'),
    url(r'^staffprofile/$', views.staffview.as_view(), name='staff_profile'),
    url(r'^addstaff/$', views.AddStaff.as_view(), name='addstaff')

 ]

record/models.py
from django.db import models
from django.core.validators import MinValueValidator

landusechoices = (('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Recreational', 'Recreational'), ('Industrial', 'Industrial'), ('Mixeduse', 'Mixeduse'))
position_choices = (('Inspector','Inspector'),('Recommending Officer','Recommending Officer'),('Charting Officer', 'Charting Officer'),('Approving Officer', 'Approving Officer'), ('Others', 'Others'), ('Corp Member','Corp Member'))
sex_choices = (('Male', 'Male'), ('Female','Female'))

class application(models.Model):
    sn = models.IntegerField(default=0)
    date_of_registration = models.DateField(default='01/01/2017')
    applicant = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    registration_plan_number = models.CharField(max_length=20)
    type_of_use = models.CharField(choices=landusechoices, max_length=15)
    no_of_floors = models.IntegerField()
    amount = models.IntegerField()
    treasury_receipt_number = models.CharField(max_length=25)
    inspector = models.ForeignKey('staff', related_name='staff_inspector', on_delete=models.SET_NULL, null=True)
    recommending_officer = models.ForeignKey('staff', related_name='staff_recommending_officer', on_delete=models.SET_NULL, null=True)
    charting_officer = models.ForeignKey('staff', related_name='staff_charting_officer', on_delete=models.SET_NULL, null=True)
    approving_officer = models.ForeignKey('staff', related_name='staff_approving_officer', on_delete=models.SET_NULL, null=True)
    luc_no = models.CharField(max_length=10)



class staff(models.Model):
    name = models.CharField(max_length=25)
    position = models.CharField(choices= position_choices, default='Others', max_length=100)
    sex = models.CharField(choices=sex_choices, max_length=6)
    profile_photo = models.FileField(upload_to='profile_photo', default='profile_photo')


    def __str__(self):
        return self.name

record/views.py
from django.shortcuts import render
from .models import application, staff
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, TemplateView
from .filters import applicationsfilter
from django.urls import reverse_lazy

class indexview(ListView):
    model = application
    context_object_name = 'applications'
    template_name = 'record/index.html'
    queryset = application.objects.all().order_by('-id')[:3]

class applicationsview(ListView):
    model = application
    context_object_name = 'applications'
    template_name = 'record/applications.html'
    paginate_by = 10
    queryset = application.objects.all()

class applicationupdate(UpdateView):
    model = application
    fields = ['sn', 'date_of_registration', 'applicant', 'location', 'registration_plan_number', 'type_of_use', 'no_of_floors', 'amount', 'treasury_receipt_number', 'inspector', 'recommending_officer', 'charting_officer', 'approving_officer', 'luc_no']
    success_url = '../applications'

class applicationdelete(DeleteView):
    model = application
    success_url = reverse_lazy('records:applications')


class mapsview(TemplateView):
    template_name = 'record/maps.html'


class CreateApplication(CreateView):
    model = application
    fields = ['sn', 'date_of_registration', 'applicant', 'location', 'registration_plan_number', 'type_of_use', 'no_of_floors', 'amount', 'treasury_receipt_number', 'inspector', 'recommending_officer', 'charting_officer', 'approving_officer', 'luc_no']
    success_url = '../applications'

def search(request):
    applications = application.objects.all()
    application_filter = applicationsfilter(request.GET, queryset=applications)
    return render(request, 'record/search.html', {'filter': application_filter})


class staffview(ListView):
    template_name = 'record/staff.html'
    model = staff
    context_object_name = 'staffs'

class AddStaff(CreateView):
    model = staff
    template_name = 'record/add_staff.html'
    fields = '__all__'
    context_object_name = 'form'
    success_url = reverse_lazy('records:staff_profile')

templates/record/add_staff.html
{% extends 'record/form_template.html' %}
{% block title %} Add a Staff {% endblock %}

{% block wizardcontainer %}
  <div class="wizard-container">

		                <div class="card wizard-card" data-color="orange" id="wizardProfile">
		                    <form action="" method="post" enctype="multipart/form-data">
		                <!--        You can switch " data-color="orange" "  with one of the next bright colors: "blue", "green", "orange", "red", "azure"          -->

		                    	<div class="wizard-header text-center">
		                        	<h3 class="wizard-title"><span><img class="logoimage" src="/static/assets/img/ogun%20state%20emblem.png"></span>&nbsp;  Add a Staff </h3> <br>

		                    	</div>
                                {% if user.is_authenticated %}
								<div class="wizard-navigation">

									<div class="progress-with-circle">
									     <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
									</div>
									<ul>
			                            <li>
											<a href="#page1" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-user"></i>
												</div>
												About
											</a>
										</li>
			                            <li>
											<a href="#page3" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-map"></i>
												</div>
												Profile Picture
											</a>
										</li>
			                        </ul>
								</div>
		                        <div class="tab-content">

		                            <div class="tab-pane" id="page1">
		                            	<div class="row">

                                            {% load widget_tweaks %}
                                            <div class="col-md-2"></div>
                                            <div class="col-md-8">
                                                {{ form.errors }}
                                                <br>
                                                    <div class="form-group">
                                                        <label>Name <small>(required)</small></label>
                                                         {{ form.name|attr:"class:form-control"|attr:"placeholder:Name"  }}
                                                    </div>
                                                    <div class="form-group">
                                                        <label>Position <small>(required)</small></label>
                                                          {{ form.position|attr:"class:form-control"|attr:"placeholder:Recommending Officer or Site Inspector"  }}
                                                    </div>
                                                    <div class="form-group">
                                                        <label>Sex <small>(required)</small></label>
                                                          {{ form.sex|attr:"class:form-control"|attr:"placeholder:Sex"  }}
                                                    </div>
                                                      {% csrf_token %}
                                            </div>
                                        <div class="col-md-2"></div>
                                        </div>

		                            </div>
		                            <div class="tab-pane" id="page3">
		                                <h5 class="info-text"> Upload your Profile Picture?</h5>
		                                <div class="row">
		                                    <div class="col-sm-8 col-sm-offset-2">
		                                        <div class="form-group">
                                                            <label>Profile Photo <small>(required)</small></label>
                                                            {{ form.profile_photo|attr:"text-center"  }}
                                                    </div>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
                                <div class="wizard-footer">
                                     <div class="text-center">
                                         <input type='button' class='btn btn-next btn-fill btn-warning btn-wd' name='next' value='Next' />
                                     </div>
		                            <div class="pull-right">
                                        <button type='submit' class='btn btn-finish btn-fill btn-warning btn-wd' name='finish' value='Finish'>Submit</button>
		                            </div>

		                            <div class="pull-left">
		                                <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Previous' />
		                            </div>
		                            <div class="clearfix"></div>
		                        </div>
                                    {% else %}
                                    <h5 class="text-center"> <a href="{% url 'account_login' %}">  You are not allowed to perform this action. Login to ad a Staff </a></h5>
                                {% endif %}

		                    </form>
		                </div>
		            </div> <!-- wizard container -->
{% endblock %}

templates/record/application_form.html
{% extends 'record/base.html' %}


{% block header-title %}
	<title>IJZPO: New Application</title>
{% endblock %}

{% block title %}
{% endblock %}


{% block content %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{# Display a form #}

<form class="applicationform" action="" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Submit
    </button>
  {% endbuttons %}
</form>
{% endblock %}

templates/record/applications.html
{% extends 'record/base.html' %}


{% block header-title %}
	<title>IJZPO: Applications</title>
{% endblock %}

{% block title %}
<h4 class="title">Applications</h4>
    <hr>
{% endblock %}


{% block content %}
<div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped">
                                    <thead>
                                        <th>ID</th>
                                        <th>Reg Date</th>
                                    	<th>Applicant</th>
                                    	<th>Location</th>
                                    	<th>Reg Plan No</th>
                                    	<th>Type of Use</th>
                                        <th>No of Floors</th>
                                    	<th>Amount</th>
                                    	<th>Treasury Receipt No</th>
                                    	<th>Inspector</th>
                                        <th>Recommending Officer</th>
                                        <th>Charting Officer</th>
                                        <th>Approving Officer</th>
                                        <th>LUC No</th>
                                    </thead>
                                    <tbody>
                                    {% for application in applications %}
                                        <tr>
                                        	<td>{{ application.sn }}</td>
                                        	<td>{{ application.date_of_registration }}</td>
                                        	<td>{{ application.applicant }}</td>
                                        	<td>{{ application.location }}</td>
                                        	<td>{{ application.registration_plan_number }}</td>
                                            <td>{{ application.type_of_use }}</td>
                                        	<td>{{ application.no_of_floors }}</td>
                                        	<td>{{ application.amount }}</td>
                                        	<td>{{ application.treasury_receipt_number }}</td>
                                        	<td>{{ application.inspector }}</td>
                                            <td>{{ application.recommending_officer }}</td>
                                        	<td>{{ application.charting_officer }}</td>
                                        	<td>{{ application.approving_officer }}</td>
                                            <td>{{ application.luc_no }}</td>
                                            {% if user.is_authenticated %}
                                             <td><a href="{% url 'records:updateapplication' application.id %}"><span class="fa fa-edit"></span></a></td>
                                            <td><form method="post" action="{% url 'records:deleteapplication' application.id %}">{% csrf_token %}<button class="fa-submit confirm-delete" type="submit"><span class="fa fa-trash"></span> </button></form></td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
    {% endif %}

                            </div>
{% endblock %}

templates/record/base.html
<!doctype html>
<html lang="en">
<head>

    <!-- IJZPO Applications Database
    Written by Osewa Dare Joshua for
    PlanShare Technologies
    http://plansharetech.com -->

	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="/static/assets/img/ogunemblemfavicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />


    {% block header-title %}
	<title>IJZPO: Dashboard</title>
    {% endblock %}

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="/static/assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- PiChart CSS -->
    <link href="/static/assets/css/pie.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="/static/assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="/static/assets/css/light-bootstrap-dashboard.css" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="/static/assets/css/demo.css" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="/static/assets/css/font-awesome.min.css" rel="stylesheet"/>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="/static/assets/css/pe-icon-7-stroke.css" rel="stylesheet" />


    <link rel="stylesheet" href="/static/assets/css/user-profiles-list-small.css">

</head>

<body>

<div class="wrapper">
    <div class="sidebar" data-color="green" data-image="/static/assets/img/oguninfrastructure.jpg">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <img class="logoimage" src="/static/assets/img/ogun%20state%20emblem.png">
                <a href="{% url 'records:index' %}" class="simple-text">
                    Ijebu-Ode Zonal Planning Office
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="{% url 'records:index' %}">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li>
                    <a href="{% url 'records:applications' %}">
                        <i class="pe-7s-note2"></i>
                        <p>Applications</p>
                    </a>
                </li>

                 <li>
                    <a href="{% url 'records:staff_profile' %}">
                        <i class="pe-7s-user"></i>
                        <p>Staff Profile</p>
                    </a>
                </li>

                <li>
                    <a href="{% url 'records:maps' %}">
                        <i class="pe-7s-map-marker"></i>
                        <p>Maps</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Ijebu-Ode Zonal Planning Office</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="{% url 'records:index' %}" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
                            </a>
                        </li>
                        <li>
                           <a href="{% url 'records:search' %}">
                                <i class="fa fa-search"></i>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">

                        {%  if user.is_authenticated %}
                         <li>
                            <a>
                                Hello, {{ user }}
                            </a>
                        </li>
                            <li class="dropdown">

                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                  <span class="fa fa-plus-square"></span> New
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                   <li><a href="{% url 'records:createapplication' %}">New Application</a> </li>
                               <li><a href="{% url 'records:addstaff' %}">New Staff</a></li>
                              </ul>
                        </li>
                            <li class="dropdown">

                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="fa fa-user"></span> Account
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'account_change_password' %}">Change Password</a></li>
                              </ul>
                        </li>
                        <li>
                            <a href="{% url 'account_logout' %}">
                                Log out
                            </a>
                        </li>
                       {% else %}
                             <li>
                            <a href="{% url 'account_signup' %}">
                                Signup
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'account_login' %}">
                                Login
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                {% block title %}<h4 class="title">Most Recent Applications</h4>
                                {% endblock %}
                            </div>
                            {% block content %}
                            {% endblock %}
                        </div>

                    </div>


        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="http://ogunstate.gov.ng/ogsurpb/">
                                Ogun State Urban and Regional Planning Board
                            </a>
                        </li>
                        <li>
                            <a href="http://ogunstate.gov.ng/mup/">
                                Ministry of Urban and Physical Planning
                            </a>
                        </li>

                    </ul>
                </nav>
                <p class="copyright pull-right">
                    <a class="nohover" href="http://www.plansharetech.com"> &copy; 2017 Delicately Crafted by PlanShare Technologies</a>
                </p>
            </div>
        </footer>


    </div>
</div>

        </div>
    </div>
</div>
</body>

    <!--   Core JS Files   -->
    <script src="/static/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
	<script src="/static/assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="/static/assets/js/bootstrap-checkbox-radio-switch.js"></script>

	<!--  Charts Plugin -->
	<script src="/static/assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="/static/assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="/static/assets/js/light-bootstrap-dashboard.js"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="/static/assets/js/demo.js"></script>

    <script src="/static/assets/js/index.js"></script>

    <script src="/static/assets/js/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).on('click', '.confirm-delete', function(){
        return confirm('Are you sure you want to delete this?');
    })</script>


</html>

templates/record/index.html
x{% extends 'record/base.html' %}


{% block header-title %}
	<title>IJZPO: Dashboard</title>
{% endblock %}

{% block title %}
    <h4 class="title">DASHBOARD</h4>
    <hr>
{% endblock %}


{% block content %}

    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title text-center">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
           Stats</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse in">
          <div class="panel-body">
              <div class="row">
            <div class="box col-md-2">
              <div class="box__header">
                <h3 class="box__header-title">Total</h3>
              </div>
              <div class="box__body">
                <div class="stats stats--main">
                  <div class="stats__amount">{{ applications_length}}</div>
                  <div class="stats__caption"><a class="stats__caption" href="{% url 'records:applications' %}" >Applications</a>
                  </div>
                </div>

              </div>
            </div>
              <div class="box col-md-2">
              <div class="box__header">
                <h3 class="box__header-title">Total</h3>
              </div>
              <div class="box__body">
                <div class="stats stats--main">
                  <div class="stats__amount">{{ staff_length}}</div>
                  <div class="stats__caption"><a class="stats__caption" href="{% url 'records:staff_profile' %}" >Staff</a>
                  </div>
                </div>

              </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                <main>
                      <section>
                        <div class="col-md-6 pieID pie">

                        </div>
                              <div class="col-md-3">
                                <ul class="pieID legend">
                                    <li>
                                    <em>Residential</em>
                                    <span>{{ residential_len }}</span>
                                  </li>
                                    <li>
                                    <em>Commercial</em>
                                    <span>{{ commercial_len }}</span>
                                  </li>
                                    <li>
                                    <em>Mixed Use</em>
                                    <span>{{ mixed_len }}</span>
                                  </li>
                                    <li>
                                    <em>Recreational</em>
                                    <span>{{ recreational_len }}</span>
                                  </li>
                                    <li>
                                    <em>Industrial</em>
                                    <span>{{ industrial_len }}</span>
                                  </li>
                                </ul>
                              </div>

                      </section>
                    </main> </div>
            </div>
                  <div class="col-md-1"></div>
            <div class="box col-md-2">
              <div class="box__header comingsoon">
                <h3 class="box__header-title comingsooncaption">Coming Soon!!!</h3>
              </div>
              <div class="box__body comingsoon">
                <div class="stats stats--main">
                  <div class="stats__caption"><span class="fa fa-map-pin"></span>&nbsp;<a class="stats__caption" href="{% url 'records:maps' %}" >View on Map</a>
                  </div>
                </div>

              </div>
            </div>
    </div>
          </div>
        </div>
      </div>
        <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title text-center">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
               Latest Applications</a>
              </h4>
            </div>
            <div id="collapse2" class="panel-collapse collapse in">
              <div class="panel-body">
                  <div class="row">
                      <div class="content table-responsive table-full-width">
        <table class="table table-hover table-striped">
        {% if applications_length > 0 %}
            <thead>
                <th>ID</th>
                <th>Reg Date</th>
                <th>Applicant</th>
                <th>Location</th>
                <th>Reg Plan No</th>
                <th>Type of Use</th>
                <th>No of Floors</th>
                <th>Amount</th>
                <th>Treasury Receipt No</th>
                <th>Inspector</th>
                <th>Recommending Officer</th>
                <th>Charting Officer</th>
                <th>Approving Officer</th>
                <th>LUC No</th>
            </thead>
        {% endif %}
            <tbody>
            {% for application in applications %}
                <tr>
                    <td>{{ application.sn }}</td>
                    <td>{{ application.date_of_registration }}</td>
                    <td>{{ application.applicant }}</td>
                    <td>{{ application.location }}</td>
                    <td>{{ application.registration_plan_number }}</td>
                    <td>{{ application.type_of_use }}</td>
                    <td>{{ application.no_of_floors }}</td>
                    <td>{{ application.amount }}</td>
                    <td>{{ application.treasury_receipt_number }}</td>
                    <td>{{ application.inspector }}</td>
                    <td>{{ application.recommending_officer }}</td>
                    <td>{{ application.charting_officer }}</td>
                    <td>{{ application.approving_officer }}</td>
                    <td>{{ application.luc_no }}</td>
                    {% if user.is_authenticated %}
                         {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>
                  </div>
              </div>
            </div>
          </div>
    </div>
    <hr>



{% endblock %}